# 此工作流使用的操作未获得 GitHub 认证。
# 它们由第三方提供，并受单独的服务条款、隐私政策和支持文档约束。

name: Dependency Review Multi-Environment

on:
  pull_request:
    branches: [ "main" ]
       push: 
  branches: [ "main" ] 
  schedule:
    - cron: '0 0 * * 0'  # 每周日 00:00 UTC

permissions:
  contents: read
  pull-requests: write  # 用于在拉取请求中添加评论

jobs:
  dependency-review:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
    runs-on: ${{ matrix.os }}
    name: Dependency Review on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    permissions:
      contents: read
      pull-requests: write  # 用于在拉取请求中添加评论

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 依赖性审查
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          comment-summary-in-pr: always
          license-check: true
          vulnerability-check: true