# 此工作流使用的操作未获得 GitHub 认证。
# 它们由第三方提供，并受单独的服务条款、隐私政策和支持文档约束。

name: DevSkim Multi-Environment Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '26 2 * * 6'

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9, 3.10, 3.11,3.12, 3.13, 3.14]
    runs-on: ${{ matrix.os }}
    name: DevSkim Scan on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行 DevSkim 扫描器
        uses: microsoft/DevSkim-Action@v1

      - name: 上传 DevSkim 扫描结果到 GitHub 安全标签
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: devskim-results.sarif