# 此工作流使用的操作未获得 GitHub 认证。
# 它们由第三方提供，并受单独的服务条款、隐私政策和支持文档约束。

name: Multi-Environment Pysa Analysis

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '33 5 * * 3'

permissions:
  contents: read

jobs:
  pysa-analysis:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13]
    runs-on: ${{ matrix.os }}
    name: Pysa on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行 Pysa
        uses: facebook/pysa-action@f46a63777e59268613bd6e2ff4e29f144ca9e88b
        with:
          repo-directory: './'
          requirements-path: 'requirements.txt'
          infer-types: true
          include-default-sapp-filters: true