# 此工作流使用的操作未获得 GitHub 认证。
# 它们由第三方提供，并受单独的服务条款、隐私政策和支持文档约束。

name: Python Dependency Audit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'  # 每周日 00:00 UTC

permissions:
  contents: read
  security-events: write

jobs:
  audit:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    runs-on: ${{ matrix.os }}
    name: Audit on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行 pip-audit
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt
          vulnerability-service: OSV
          summary: true